export * from './city.model'
export * from './subject.model'
export * from './semester.model'
export * from './examination-period.model'
export * from './exam.model'
export * from './professor.model'
export * from './title.model'
export * from './student.model'
export * from './student-exam.model'

